#!/usr/bin/env ruby
require_relative 'month'
require_relative 'year'

if ARGV.length == 2
  #params order: month string, year
  month = Month.new(ARGV[0], ARGV[1])
  print month.to_s
elsif ARGV.length == 1
  #params order: year
  year_instance = Year.new(ARGV[0])
  print year_instance.to_s
else
  month = Month.new('April', 2014)
  print month.to_s
end
